# Development environment. Extends docker-compose.yml

server:
  ports:
    - "8080:8080"


app:
  command: python manage.py runserver 0.0.0.0:8080
  volumes:
    - ./app_dir/:/app
  environment:
    DJANGO_DEBUG: 'True'
